version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zwash
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
      - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.show-sql = false
      - spring.jpa.generate-ddl = true
      - spring.jpa.hibernate.ddl-auto = create-drop
      - spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
      - spring.mvc.throw-exception-if-no-handler-found=true
      - spring.web.resources.add-mappings=false
      - logging.file.name=logs
      - logging.level.root=DEBUG
      - springdoc.swagger-ui.operationsSorter=method
      - springdoc.api-docs.path=/api-docs
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - server.port=7001
      - logging.level.org.springframework=DEBUG
      - spring.main.allow-bean-definition-overriding=true
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-password
      POSTGRES_DB: zwash
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
